feat: タグによる検索結果件数が表示されるよう修正しました。
nablarch/nablarch-example-web pull request #86
Opened 2023-01-30 05:00 UTC by sukegawatakashitis

### 修正内容

- タグによる検索結果件数が表示されるよう修正しました。

2023-02-06 01:05 UTC, kumagoro1202 requested changes

2023-02-06 01:55 UTC, sukegawatakashitis commented on src/main/webapp/WEB-INF/tags/listSearchResult/listSearchResult.tag
> +<n:set var="pagination" name="${resultSetName}.pagination" scope="request" />
JSPからの呼び出しにメリットがあると考えましたが、変数名バッティングのデメリットの方が大きいため、デフォルトのpageスコープに戻しました。https://github.com/nablarch/nablarch-example-web/pull/86/commits/06681a3722d386dd09a11ed9103dbeb673e5ea6a

2023-02-06 02:04 UTC, kumagoro1202 commented on src/main/webapp/WEB-INF/tags/listSearchResult/listSearchResult.tag
> +<n:set var="pagination" name="${resultSetName}.pagination" scope="request" />
pageスコープに戻っていません。省略するとrequestスコープです。

2023-02-07 05:43 UTC, sukegawatakashitis commented on src/main/webapp/WEB-INF/tags/listSearchResult/listSearchResult.tag
> +<n:set var="pagination" name="${resultSetName}.pagination" scope="request" />
失礼しました。こちらで修正しました。https://github.com/nablarch/nablarch-example-web/pull/86/commits/7d39e94fa04b88d63956b706b319ed9b40c9081f

2023-02-07 08:02 UTC, kumagoro1202 approved these changes

2023-02-07 08:02 UTC, merged