独自実装されたコード値バリデーションを標準機能に置き換えました
nablarch/nablarch-example-web pull request #99
Opened 2023-07-19 03:31 UTC by chupaaaaaaan

2023-07-19 08:39 UTC, chupaaaaaaan commented
コンフリクトを解消しました。

2023-07-20 08:09 UTC, kumagoro1202 requested changes

2023-07-20 08:09 UTC, kumagoro1202 commented on src/main/java/com/nablarch/example/app/web/common/code/CodeEnum.java
> +    @Override
Javadocをもう少し詳しく書いてJavadocを記載するためにOverrideしてることがわかるようにしてください。

2023-07-20 09:01 UTC, chupaaaaaaan commented on src/main/java/com/nablarch/example/app/web/common/code/CodeEnum.java
> +    @Override
WithValueの役割をJavadocに追記しました。

2023-07-20 11:11 UTC, kumagoro1202 requested changes

2023-07-20 11:11 UTC, kumagoro1202 commented on src/main/java/com/nablarch/example/app/web/common/code/CodeEnum.java
> +    @Override
```java
    /**
     * コード値を返却する。
     * コード値はバリデーション時に許容する列挙値としても使用する。
     * @return コード値
     * @see nablarch.core.validation.ee.EnumElement
     */
    @Override // override for Javadoc
    String getValue();
```
とかの方が私はわかりやすいと思います。

2023-07-20 23:46 UTC, chupaaaaaaan commented on src/main/java/com/nablarch/example/app/web/common/code/CodeEnum.java
> +    @Override
私も上記の方が分かり易いと思いました。いずれも修正しました。

2023-07-24 01:25 UTC, kumagoro1202 approved these changes

2023-07-24 01:26 UTC, merged